blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name = 'content'),
    url(r'^$', Page.as_view(), name = 'page'),
]

csscontent/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name='content'),
    url(r'^mengenal/cascadingstylesheet/$', ContentList.as_view(), name='definisi'),
    url(r'^$', Page.as_view(), name='page'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^django/', include('djangocontent.urls', namespace = 'django')),
    url(r'^oop/', include('oopcontent.urls', namespace = 'oop')),
    url(r'^python/', include('pythoncontent.urls', namespace = 'python')),
    url(r'^bootstrap/', include('bootstrapcontent.urls', namespace = 'bootstrap')),
    url(r'^dom/', include('domcontent.urls', namespace = 'dom' )),
    url(r'^js/', include('jscontent.urls', namespace = 'js' )),
    url(r'^css/', include('csscontent.urls', namespace = 'css' )),
    url(r'^html/', include('htmlcontent.urls', namespace = 'html' )),
    url(r'^tutorial/$', Tutorial.as_view(), name='tutorial'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csscontent/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Content(models.Model):
    title       = models.CharField(blank=True, max_length=255)
    subtitle    = models.CharField(blank=True, max_length=255)
    cover       = models.ImageField(upload_to="cover/css/", default="default.png", blank=True)
    content     = models.TextField(blank=True)
    image       = models.ImageField(upload_to="image/css/", default="default.png", blank=True)
    caption    = models.TextField(blank=True)

    title1      = models.CharField(blank=True, max_length=255)
    content1    = models.TextField(blank=True)
    code1       = models.TextField(blank=True)
    text1       = models.TextField(blank=True)
    image1      = models.ImageField(upload_to="image/css/", default="default.png", blank=True)
    caption1    = models.TextField(blank=True)

    title2      = models.CharField(blank=True, max_length=255)
    content2    = models.TextField(blank=True)
    code2       = models.TextField(blank=True)
    text2       = models.TextField(blank=True)
    image2      = models.ImageField(upload_to="image/css/", default="default.png", blank=True)
    caption2    = models.TextField(blank=True)


    title3      = models.CharField(blank=True, max_length=255)
    content3    = models.TextField(blank=True)
    code3       = models.TextField(blank=True)
    text3       = models.TextField(blank=True)
    image3      = models.ImageField(upload_to="image/css/", default="default.png", blank=True)
    caption3    = models.TextField(blank=True)

    CATEGORY    = (
                    ('html','html'),
                    ('css','css'),
                    ('js','js'),
                    ('dom','dom'),
                    ('bootstrap','bootstrap'),
                    ('python','python'),
                    ('oop','oop'),
                    ('django','django'),
                  )
    category    = models.CharField(max_length=255, choices=CATEGORY)



    author     = models.CharField(max_length=255)
    publish     = models.DateTimeField(auto_now_add=True)
    slug        = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.title)
        super().save()

    def __str__(self):
        return "{}.{}".format(self.id, self.title)

csscontent/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
# Create your views here.
from .models import *
class Page(ListView):
    model               = Content
    template_name       = "css/page_list.html"
    context_object_name = 'content_list'
class ContentList(ListView):
    model               = Content
    template_name       = "css/content_list.html"
    context_object_name = 'content_list'
class ContentDetail(DetailView):
    model               = Content
    template_name       = 'css/content_detail.html'
    context_object_name = 'content'
    def get_context_data(self, *args, **kwargs):
        other_content = self.model.objects.filter(category = self.object.category).distinct().exclude(id = self.object.id)
        self.kwargs.update({'other_content':other_content})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

csscontent/templates/css/content_detail.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
   {{content.subtitle}}
{% endblock Title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "css/styling/definisi.css" %}">

    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8" id="article">
          <div class="card" style="border: none;">
            <div class="card-body">
              <h2 class="card-title" style="font-weight: bold;">{{content.subtitle}}</h2>
              <hr class="bg-dark mb-5">

              <img class="img-fluid mb-4" src="{{content.cover.url}}" alt="cover" width="780px">
              <div class="card-text">
                <p>{{content.content|linebreaksbr}}</p>
                <img class="img-fluid" id="gambar" src="{{content.image.url}}" alt=""/>
                <p class="mt-5">{{content.caption|linebreaksbr}}</p>
                <h4 class="mt-4 mb-3">{{content.title1}}</h4>
                <p>{{content.content1|linebreaksbr}}</p>
                  <pre class="mb-5" data-codetype="CSS" style="margin-left: 0px;"><code>{{content.code1|linebreaksbr}}</code></pre>
                <p>{{content.text1|linebreaksbr}}</p>
                <img class="img-fluid" id="gambar" src="{{content.image1.url}}" alt=""/>
                <p class="mt-5">{{content.caption1|linebreaksbr}}</p>

                <h4 class="mt-5 mb-3">{{content.title2}}</h4>
                <p>{{content.content2|linebreaksbr}}</p>
                  <pre data-codetype="CSS" style="margin-left: 0px;"><code>{{content.code2|linebreaksbr}}</code></pre>
                <p>{{content.text2}}</p>
                <img class="img-fluid" id="gambar" src="{{content.image2.url}}" alt=""/>
                <p class="mt-5">{{content.caption2|linebreaksbr}}</p>
                <h4 class="mt-5 mb-3">{{content.title3}}</h4>
                <p>{{content.content3|linebreaksbr}}</p>
                  <pre data-codetype="HTML"  style="margin-left: 0px;"><code>{{content.code3|linebreaksbr}}</code></pre>
                <p>{{content.text3|linebreaksbr}}</p>
                <img class="img-fluid" id="gambar" src="{{content.image3.url}}" alt="" />
                <p class="mt-5">{{content.caption3|linebreaksbr}}</p>
              </div>
            </div>
          </div>
        </div>


        <div class="col-sm-12 col-lg-4" style="margin-top: 50px;" id="sidebar">
          <div class="card shadow">
          <div class="card-body">
            <h4 class="text-center">Artikel Terkait</h4>
            <ul class="list-group">
              <a class="text-dark" id="title" href="{% url 'css:definisi'%}">
               <li class="list-group-item" id="title">Mengenal CSS</li>
              </a>
              {% for content in other_content  %}
                <a class="text-dark" id="title" href="{% url 'css:content' content.slug %}">
                  <li class="list-group-item" id="title">{{content.title}}</li>
                </a>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="card shadow mt-5 mb-5">
          <div class="card-body">
              <h4 class="text-center">Tutorial Lainnya</h4>
              <ul class="list-group">
                <a href="{% url 'html:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/html.png' %}" alt="" width="30px">
                    <span id="title">HTML</span>
                  </li>
                </a>
                <a href="{% url 'js:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                    <span id="title">Javascript</span>
                  </li>
                </a>
                <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                    <span id="title">DOM</span>
                  </li>
                </a>
                <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                    <span id="title">Bootstrap</span>
                  </li>
                </a>
                <a href="{% url 'python:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                    <span id="title">Python</span>
                  </li>
                </a>
                <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                    <span id="title">OOP</span>
                  </li>
                </a>
                <a href="{% url 'django:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                    <span id="title">Django</span>
                  </li>
                </a>
              </ul>
          </div>
        </div>

      </div>
    </div>

{% endblock Contents %}

csscontent/templates/css/content_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    CSS
{% endblock Title %}

{% block page_title %}
    Mengenal CSS
{% endblock page_title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "css/styling/definisi.css" %}">
    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8 mb-5" id="article">
          <div class="card" style="border: none;">
            <div class="card-body">
              <h2 class="card-title" style="font-weight: bold; ">Mengenal Dasar CSS</h2>
              <hr class="bg-dark mb-5">

              <img class="img-fluid mb-5" src="{% static 'img/cover/css.png' %}" alt="cover" width="780px">

              <div class="card-text">
                <p><i>"CSS adalah kumpulan kode yangan digunakan untuk mendefinisikan desaign dari bahasa markup, salah satunya HTML."</i></p>
                <p> Singkatnya dengan menggunakan CSS kita dapat dengan mudah secara keseluruhan mengubah tampilan halaman web sesuai keinginan kita. File pada CSS berekstensi .css.</p>
                <p>Sejarah singkat, Nama CSS didapat dari fakta bahwa setiap deklarasi style yang berbeda dapat diletakkan secara berurutan, yang kemudian membentuk hubungan <b>ayah-anak (parent-child)</b> pada setiap style.</p>
                <p>CSS sendiri merupakan sebuah teknologi internet yang direkomendasikan oleh World Wide Web Consortium atau W3C pada tahun 1996. Setelah CSS distandardisasikan, Internet Explorer dan Netscape melepas browser terbaru mereka yang telah sesuai atau paling tidak hampir mendekati dengan standar CSS. <br>Jika ingin mengetahui lebih spesifik lagi tentang CSS silahkan kunjungi website resminya di <a href="https://www.w3.org/Style/CSS/">https://www.w3.org/Style/CSS/</a></p>

                <h3 class="mt-5 mb-3">Penggunaan Kode CSS</h3>
                <p>CSS datang bersama dengan HTML tag. Untuk menginputkan kode css 3 metode antara lain :</p>

                <!-- Metode Inline Style -->
                <h4>1. Metode Inline Style</h4>
                <p style="margin: 0px 10px 0px 25px;">Cara menginputkan sebuah kode CSS secara langsung ke dalam tag html dg menggunakan atribut. <br><br>inline.html</p>

                  <pre data-codetype="HTML"><code>&lt;!DOCTYPE html&gt;<br> &lt;html&gt;<br>  &lt;head&gt;<br>   &lt;title&gt;Metode Inline CSS&lt;/title&gt;<br>  &lt;/head&gt;<br>  &lt;body&gt;<br>   &lt;p style="color: red; font-family: monospace; font-size: 20px;"&gt;<br>     Paragraf ini menggunakan metode inline style css <br>   &lt;/p&gt; <br>  &lt;/body&gt; <br> &lt;/html&gt;</code></pre>

                <p style="margin: 0px 10px 0px 25px;">Output yang dihasilkan :</p>
                <img class="img-fluid m-4" src="{% static 'img/property/css/inline.png' %}" alt="">

                <!-- Metode Internal CSS -->
                <h4>2.  Metode Internal CSS</h4>
                <p style="margin: 0px 10px 0px 25px;">Disebut juga <em>Embedded Stylesheet</em> digunakan untuk memisahkan kode  css dari tag HTML. Kekurangan dari metode ini ialah jika ingin membuat beberapa halaman dan tampilan yang sama, maka setiap halaman akan memiliki kode CSS yang sama juga.<br>Contoh :<br><br>internal.html</p>

                  <pre data-codetype="HTML"><code>&lt;!DOCTYPE html&gt;<br> &lt;html&gt;<br>  &lt;head&gt;<br>   &lt;title&gt;Metode Internal CSS&lt;/title&gt;<br>   &lt;style type="text/css"&gt; <br>    p{<br>     color: blue;<br>     font-family: arial;<br>     font-size: 20px;<br>    }<br>   &lt;/style&gt;<br>  &lt;/head&gt;<br>  &lt;body&gt;<br>   &lt;p&gt;Paragraf ini menggunakan metode internal css&lt;/p&gt;<br>  &lt;/body&gt; <br> &lt;/html&gt;</code></pre>

                <p style="margin: 0px 10px 0px 25px;">Output yang dihasilkan :</p>
                <img class="img-fluid m-4" src="{% static 'img/property/css/internal.png' %}" alt="">

                <!-- Metode Eksternal CSS -->
                <h4>3.  Metode Eksternal CSS</h4>
                <p style="margin: 0px 10px 0px 25px;">Digunakan untuk <em>"mengangkat"</em> kode CSS tsb ke dalam sebuah file tersendiri yang terpisah sepenuhnya dari halaman HTML.<br>Contoh :<br><br>eksternal.html</p>

                  <pre data-codetype="HTML"><code>&lt;!DOCTYPE html&gt;<br> &lt;html&gt;<br>  &lt;head&gt;<br>   &lt;title&gt;Metode Internal&lt;/title&gt;<br>   &lt;!-- atau bisa juga menggunakan tag @import url(…) --&gt;<br>   &lt;style type="text/css"&gt; <br>    h1{<br>     @import url(css/styles.css);<br>    }<br>   &lt;/style&gt;<br>  &lt;/head&gt;<br>  &lt;body&gt;<br>   &lt;p&gt;Paragraf ini menggunakan metode eksternal css&lt;/p&gt;<br>  &lt;/body&gt; <br> &lt;/html&gt;</code></pre>

                <p style="margin: 0px 10px 0px 35px;">styles.css</p>

                  <pre data-codetype="CSS"><code>h1{<br> color: green;<br> font-family: sans-serif;<br> font-size: 20px;<br>}</code></pre>

                <p style="margin: 0px 10px 0px 25px;">Output yang dihasilkan :</p>
                <img class="img-fluid m-4" src="{% static 'img/property/css/eksternal.png' %}" alt="">
              </div>
            </div>
          </div>
      </div>

      <div class="col-sm-12 col-lg-4" style="margin-top: 50px;" id="sidebar">
        <div class="card shadow">
            <div class="card-body">
              <h4 class="text-center">Artikel Terkait</h4>
              <ul class="list-group">
                {% for content in content_list  %}
                  <a href="{% url 'css:content' content.slug %}" class="text-dark" id="title">
                    <li class="list-group-item" id="title">{{content.title}}</li>
                  </a>
                {% endfor %}
              </ul>
            </div>
        </div>

        <div class="card shadow mt-5 mb-5">
          <div class="card-body">
            <h4 class="text-center">Tutorial Lainnya</h4>
            <ul class="list-group">
              <a class="text-dark" id="title" href="{% url 'html:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/html.png' %}" alt="" width="30px">
                  <span id="title">HTML</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'js:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                  <span id="title">Javascript</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'dom:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                  <span id="title">DOM</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'bootstrap:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                  <span id="title">Bootstrap</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'python:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                  <span id="title">Python</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'oop:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                  <span id="title">OOP</span>
                </li>
              </a>
              <a class="text-dark" id="title" href="{% url 'django:page' %}">
                <li class="list-group-item">
                  <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                  <span id="title">Django</span>
                </li>
              </a>
            </ul>
            </div>
        </div>

      </div>
    </div>



{% endblock Contents %}

csscontent/templates/css/page_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    CSS
{% endblock Title %}

{% block page_title %}
    <div class="jumbotron-fluid ml-5">
      <h1 class="display-4 text-dark">C S S</h1>
      <h2 class="text-dark mb-5">Tutorial bagi para pemula</h2>
    </div>
{% endblock page_title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "css/styling/page.css" %}">

    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12 col-lg-8 "  style="margin-bottom: 200px;" id="article">
          <div class="col-sm">
            <div class="card shadow">
              <div class="card-body">
                <a href="{% url 'css:definisi' %}" class="text-dark" id="title">Mengenal CSS</a>
              </div>
            </div>
          </div>
          <div class="col-sm">
            {% for content in content_list  %}
              <div class="card shadow">
                <div class="card-body">
                  <a href="{% url 'css:content' content.slug %}"/class="text-dark" id="title">{{content.title}}</a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="col-sm-12 col-lg-4" id="sidebar">
          <div class="card shadow">
            <div class="card-body">
              <h3 class="text-center">Tutorial Lainnya</h3>
              <ul class="list-group">
                <a href="{% url 'html:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/html.png' %}" alt="" width="30px">
                    <span id="title">HTML</span>
                  </li>
                </a>

                <a href="{% url 'js:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                    <span id="title">Javascript</span>
                  </li>
                </a>

                <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                    <span id="title">DOM</span>
                  </li>
                </a>

                <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                    <span id="title">Bootstrap</span>
                  </li>
                </a>

                <a href="{% url 'python:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                    <span id="title">Python</span>
                  </li>
                </a>

                <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                    <span id="title">OOP</span>
                  </li>
                </a>

                <a href="#" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                    <span id="title">Django</span>
                  </li>
                </a>
              </ul>
              </div>
          </div>
        </div>

      </div>
      </div>



{% endblock Contents %}