blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name = 'content'),
    url(r'^$', Page.as_view(), name = 'page'),
]

htmlcontent/urls.py
from django.conf.urls import url
from .views import *
urlpatterns =[
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name='content'),
    url(r'^mengenal/hypertext-markup-languange/$', ContentList.as_view(), name='definisi'),
    url(r'^$', Page.as_view(), name='page'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^django/', include('djangocontent.urls', namespace = 'django')),
    url(r'^oop/', include('oopcontent.urls', namespace = 'oop')),
    url(r'^python/', include('pythoncontent.urls', namespace = 'python')),
    url(r'^bootstrap/', include('bootstrapcontent.urls', namespace = 'bootstrap')),
    url(r'^dom/', include('domcontent.urls', namespace = 'dom' )),
    url(r'^js/', include('jscontent.urls', namespace = 'js' )),
    url(r'^css/', include('csscontent.urls', namespace = 'css' )),
    url(r'^html/', include('htmlcontent.urls', namespace = 'html' )),
    url(r'^tutorial/$', Tutorial.as_view(), name='tutorial'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

htmlcontent/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Content(models.Model):
    title1      = models.CharField(blank=True, max_length=255)
    cover       = models.ImageField(upload_to="cover/html/", default="default.png", blank=True)
    text1       = models.TextField(blank=True)
    title2      = models.CharField(blank=True, max_length=255)
    text2       = models.TextField(blank=True)
    title3      = models.CharField(blank=True, max_length=255)
    text3       = models.TextField(blank=True)
    title4      = models.CharField(blank=True, max_length=255)
    text4       = models.TextField(blank=True)
    title5      = models.CharField(blank=True, max_length=255)
    text5       = models.TextField(blank=True)
    title6      = models.CharField(blank=True, max_length=255)
    text6       = models.TextField(blank=True)

    code        = models.TextField(blank=True)
    text        = models.TextField(blank=True)
    image       = models.ImageField(upload_to="image/html/", default="default.png", blank=True)
    caption     = models.TextField(blank=True)

    CATEGORY    = (
                    ('html','html'),
                    ('css','css'),
                    ('js','js'),
                    ('dom','dom'),
                    ('bootstrap','bootstrap'),
                    ('python','python'),
                    ('oop','oop'),
                    ('django','django'),
                  )
    category    = models.CharField(max_length=255, choices=CATEGORY)



    author      = models.CharField(max_length=255)
    publish     = models.DateTimeField(auto_now_add=True)
    slug        = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.title1)
        super().save()

    def __str__(self):
        return "{}.{}".format(self.id, self.title1)

htmlcontent/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# Create your views here.
from .models import Content
class Page(ListView):
    model = Content
    template_name = 'html/page_list.html'
    context_object_name = 'content_list'
class ContentList(ListView):
    model = Content
    template_name = 'html/content_list.html'
    context_object_name = 'content_list'
class ContentDetail(DetailView):
    model = Content
    template_name = 'html/content_detail.html'
    context_object_name = 'content'
    def get_context_data(self, *args, **kwargs):
        other_content = self.model.objects.filter(category = self.object.category).distinct().exclude(id = self.object.id)
        self.kwargs.update({'other_content':other_content})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

htmlcontent/templates/html/content_detail.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    {{content.title1}}
{% endblock Title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "html/styling/content.css" %}">
    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

      <div class="col-sm-12 col-lg-8 mb-5" id="article">
        <div class="card" style="border: none;">
          <div class="card-body">
            <h2 class="card-title" style="font-weight: bold;">{{content.title1}}</h2>
            <hr class="bg-dark mb-5">

            <img class="img-fluid mb-5" src="{{content.cover.url}}" alt="cover" width="780px">

            <div class="card-text">
              <p>{{content.text1|linebreaksbr}}</p>

              <h4 class="mt-4 mb-2">{{content.title2|linebreaksbr}}</h4>
              <p>{{content.text2|linebreaksbr}}</p>

              <h4 class="mt-4 mb-2">{{content.title3|linebreaksbr}}</h4>
              <p>{{content.text3|linebreaksbr}}</p>

              <h4 class="mt-4 mb-2">{{content.title4|linebreaksbr}}</h4>
              <p>{{content.text4|linebreaksbr}}</p>

              <h4 class="mt-4 mb-2">{{content.title5|linebreaksbr}}</h4>
              <p>{{content.text5|linebreaksbr}}</p>

              <h4 class="mt-4 mb-2">{{content.title6|linebreaksbr}}</h4>
              <p>{{content.text6|linebreaksbr}}</p>

                  <pre id="pre">
                    <code class="html">{{content.code|linebreaksbr}}</code>
                  </pre>

              <p>{{content.text|linebreaksbr}}</p>
              <img class="img-fluid" id="image" src="{{content.image.url}}" alt="">
              <p class="mt-4">{{content.caption|linebreaksbr}}</p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-12 col-lg-4" style="margin-top: 50px;" id="sidebar">
        <div class="card shadow">
          <div class="card-body">
            <h4 class="text-center">Artikel Terkait</h4>
            <ul class="list-group">
              <a class="text-dark" id="title" href="{% url 'html:definisi'%}">
               <li class="list-group-item">Mengenal HTML</li>
             </a>
             {% for content in other_content %}
                <a class="text-dark" id="title" href="{% url 'html:content' content.slug %}">
                  <li class="list-group-item">{{content.title1}}</li>
                </a>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="card shadow mt-5 mb-5">
          <div class="card-body">
              <h4 class="text-center">Tutorial Lainnya</h4>
              <ul class="list-group">
                <a href="{% url 'css:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/css.png' %}" alt="" width="30px">
                    <span id="title">CSS</span>
                  </li>
                </a>

                <a href="{% url 'js:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                    <span id="title">Javascript</span>
                  </li>
                </a>

                <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                    <span id="title">DOM</span>
                  </li>
                </a>

                <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                    <span id="title">Bootstrap</span>
                  </li>
                </a>

                <a href="{% url 'python:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                    <span id="title">Python</span>
                  </li>
                </a>

                <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                    <span id="title">OOP</span>
                  </li>
                </a>

                <a href="{% url 'django:page' %}" class="text-dark" id="title">
                  <li class="list-group-item mb-2">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                    <span id="title">Django</span>
                  </li>
                </a>
              </ul>
          </div>
        </div>

      </div>

      </div>
    </div>
{% endblock Contents %}

htmlcontent/templates/html/content_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    HTML
{% endblock Title %}


{% block Contents %}
    <link rel="stylesheet" href="{% static "html/styling/definisi.css" %}">
    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8 mb-5" id="article">
          <div class="card" style="border: none;">
            <div class="card-body">
              <h2 class="card-title" style="font-weight: bold;">Mengenal Dasar HTML</h2>
              <hr class="bg-dark mb-5" id="hr">

              <img class="img-fluid mb-5" src="{% static 'img/cover/html.png' %}" alt="cover" width="780px;">

              <div class="card-text">
                <p>
                  <b>HTML</b> atau <b>Hypertext Markup Languange</b>   dibuat oleh <em>Tim Bernes-Lee (Seorang ahli Fisika)</em>  saat bekerja di <em>CERN (Organisasi Nuklir di Eropa)</em>. HTML adalah sebuah  yang  bahasa markup  untuk membuat sebuah halaman web, menampilkan berbagai informasi di dalam sebuah browser.
                </p>

                <h5>Kenapa HTML penting dipelajari ?</h5>
                <p>Karena html merupakan bahan dasar dalam pembuatan sebuah web.</p>

                <p>
                  Istilah yang harus dipelajari dalam HTML :
                </p>
                <p>
                  <b>Dokumen HTML</b> adalah kumpulan teks sederhana yang terdiri dari konten halaman dan tag halaman untuk menandai  konten tersebut agar dapat dibaca oleh browser.
                </p>
                <p>
                  <b>Elemen HTML</b> adalah konten halaman yang sudah ditandai oleh tag HTML.<br> <b>Ekstensi File</b> pada HTML yaitu <code class="text-dark">.html</code>.</p>
                <p>
                  <b>Tag</b>, bisa kita katakan sebagai sebuah penanda. Penanda awalan dan akhiran sebuah elemen. Tag diapit dengan kurung siku <code class="text-dark">(&lt;&#46;&#46;&#46;&gt;)&#44;</code> seperti tag <code class="text-dark">&lt;html&gt;&#46;&#46;&#46;&lt;&#47;html&gt;</code>&#46;
                </p>
                <p>
                  <b>Atribut</b> adalah bagian dari elemen yang melengkapi elemen tersebut. Atribut tersebut memiliki ciri-ciri atau nilai. Contoh : atribut href yang berfungsi menentukan alamat link dari elemen <code class="text-info">a</code> &#46;
                </p>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-lg-4" style="margin-top: 50px;"  id="sidebar">
          <div class="card shadow">
            <div class="card-body">
              <h3 class="text-center display-5">Artikel Terkait</h3>
              <ul class="list-group">
                {% for content in content_list %}
                   <a class="text-dark" id="title" href="{% url 'html:content' content.slug %}">
                    <li class="list-group-item">{{content.title1}}</li>
                  </a>
                {% endfor %}
              </ul>
            </div>
          </div>
          <div class="card shadow mt-5 mb-5">
            <div class="card-body">
                <h3 class="text-center display-5">Tutorial Lainnya</h3>
                <ul class="list-group">
                  <a href="{% url 'css:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/css.png' %}" alt="" width="30px">
                      <span id="title">CSS</span>
                    </li>
                  </a>

                  <a href="{% url 'js:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                      <span id="title">Javascript</span>
                    </li>
                  </a>

                  <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                      <span id="title">DOM</span>
                    </li>
                  </a>

                  <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                      <span id="title">Bootstrap</span>
                    </li>
                  </a>

                  <a href="{% url 'python:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                      <span id="title">Python</span>
                    </li>
                  </a>

                  <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                      <span id="title">OOP</span>
                    </li>
                  </a>

                  <a href="{% url 'django:page' %}" class="text-dark" id="title">
                    <li class="list-group-item mb-2">
                      <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                      <span id="title">Django</span>
                    </li>
                  </a>
                </ul>
            </div>
          </div>

        </div>
      </div>
    </div>



{% endblock Contents %}

htmlcontent/templates/html/page_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    HTML
{% endblock Title %}

{% block page_title %}
  <div class="jumbotron-fluid ml-5">
      <h1 class="display-4 text-dark">H T M L</h1>
      <h2 class="text-dark mb-5">Tutorial bagi para pemula</h2>
  </div>
{% endblock page_title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "html/styling/page.css" %}">

    <div class="container-fluid" style="margin-bottom: 200px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8" id="article">
          <div class="col-sm">
            <div class="card shadow">
              <div class="card-body">
                <a href="{% url 'html:definisi' %}" class="text-dark" id="title"><p id="title">Mengenal HTML</p></a>
              </div>
            </div>
          </div>
          <div class="col-sm mb-5">
            {% for content in content_list  %}
            <div class="card shadow">
              <div class="card-body">
                <a href="{% url 'html:content' content.slug %}" class="text-dark" id="title"><p id="title">{{content.title1}}</p></a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

        <div class="col-sm-12 col-lg-4" id="sidebar">
          <div class="card shadow">
            <div class="card-body">
              <h3 class="text-center">Tutorial Lainnya</h3>
              <ul class="list-group">
                <a href="{% url 'css:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/css.png' %}" alt="" width="30px">
                    <span id="title">CSS</span>
                  </li>
                </a>

                <a href="{% url 'js:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/js.png' %}" alt="" width="30px">
                    <span id="title">Javascript</span>
                  </li>
                </a>

                <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                    <span id="title">DOM</span>
                  </li>
                </a>

                <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                    <span id="title">Bootstrap</span>
                  </li>
                </a>

                <a href="{% url 'python:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                    <span id="title">Python</span>
                  </li>
                </a>

                <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                    <span id="title">OOP</span>
                  </li>
                </a>

                <a href="{% url 'django:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                    <span id="title">Django</span>
                  </li>
                </a>
              </ul>
              </div>
          </div>
        </div>

        </div>
      </div>



{% endblock Contents %}