blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name = 'content'),
    url(r'^$', Page.as_view(), name = 'page'),
]

jscontent/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name='content'),
    url(r'^mengenal/javascipt/$', ContentList.as_view(), name = 'definisi'),
    url(r'^$', Page.as_view(), name = 'page'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^django/', include('djangocontent.urls', namespace = 'django')),
    url(r'^oop/', include('oopcontent.urls', namespace = 'oop')),
    url(r'^python/', include('pythoncontent.urls', namespace = 'python')),
    url(r'^bootstrap/', include('bootstrapcontent.urls', namespace = 'bootstrap')),
    url(r'^dom/', include('domcontent.urls', namespace = 'dom' )),
    url(r'^js/', include('jscontent.urls', namespace = 'js' )),
    url(r'^css/', include('csscontent.urls', namespace = 'css' )),
    url(r'^html/', include('htmlcontent.urls', namespace = 'html' )),
    url(r'^tutorial/$', Tutorial.as_view(), name='tutorial'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jscontent/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Content(models.Model):
    title       = models.CharField(blank=True, max_length=255)
    subtitle    = models.CharField(blank=True, max_length=255)
    cover       = models.ImageField(upload_to="cover/js/", default="default.png", blank=True)
    content     = models.TextField(blank=True)
    title1      = models.CharField(blank=True, max_length=255)
    content1    = models.TextField(blank=True)
    code1       = models.TextField(blank=True)
    text1       = models.TextField(blank=True)
    image1      = models.ImageField(upload_to="image/js/", default="default.png", blank=True)
    caption1    = models.TextField(blank=True)
    title2      = models.CharField(blank=True, max_length=255)
    content2    = models.TextField(blank=True)
    code2       = models.TextField(blank=True)
    text2       = models.TextField(blank=True)
    image2      = models.ImageField(upload_to="image/js/", default="default.png", blank=True)
    caption2    = models.TextField(blank=True)
    title3      = models.CharField(blank=True, max_length=255)
    content3    = models.TextField(blank=True)
    code3       = models.TextField(blank=True)
    text3       = models.TextField(blank=True)
    image3      = models.ImageField(upload_to="image/js/", default="default.png", blank=True)
    caption3    = models.TextField(blank=True)
    title4      = models.CharField(blank=True, max_length=255)
    content4    = models.TextField(blank=True)
    code4       = models.TextField(blank=True)
    text4       = models.TextField(blank=True)
    image4      = models.ImageField(upload_to="image/js/", default="default.png", blank=True)
    caption4    = models.TextField(blank=True)
    CATEGORY    = (
                    ('html','html'),
                    ('css','css'),
                    ('js','js'),
                    ('dom','dom'),
                    ('bootstrap','bootstrap'),
                    ('python','python'),
                    ('oop','oop'),
                    ('django','django'),
                  )
    category    = models.CharField(max_length=255, choices=CATEGORY)
    author     = models.CharField(max_length=255)
    publish     = models.DateTimeField(auto_now_add=True)
    slug        = models.SlugField(blank=True, editable=False)
    def save(self):
        self.slug = slugify(self.title)
        super().save()
    def __str__(self):
        return "{}.{}".format(self.id, self.title)

jscontent/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
# Create your views here.
from .models import *
class Page(ListView):
    model = Content
    template_name= 'javascript/page_list.html'
    context_object_name = 'content_list'
class ContentList(ListView):
    model = Content
    template_name= 'javascript/content_list.html'
    context_object_name = 'content_list'
class ContentDetail(DetailView):
    model = Content
    template_name = 'javascript/content_detail.html'
    context_object_name = 'content'
    def get_context_data(self, *args, **kwargs):
        other_content = self.model.objects.filter(category = self.object.category).distinct().exclude(id = self.object.id)
        self.kwargs.update({'other_content':other_content})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

jscontent/templates/javascript/content_detail.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
   {{content.title}}
{% endblock Title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "javascript/styling/content.css" %}">

    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8" id="article">
          <div class="card" style="border: none;">
            <div class="card-body">
              <h2 class="card-title" style="font-weight: bold;">{{content.subtitle}}</h2>
              <hr class="bg-dark mb-5">
              <img class="img-fluid mb-5" src="{{content.cover.url}}" alt="cover" width="780px">
              <div class="card-text">
                <p class="mb-3">{{content.content|linebreaksbr}}</p>
                <h4 class="mb-2">{{content.title1}}</h4>
                <p>{{content.content1|linebreaksbr}}</p>
                  <pre data-codetype="HTML"><code>{{content.code1|linebreaksbr}}</code></pre>
                <p class="mt-5">{{content.text1|linebreaksbr}}</p>
                <img class="img-fluid mt-2" id="image" src="{{content.image1.url}}" style="margin-bottom: 30px;"/>
                <p>{{content.caption1|linebreaksbr}}</p>
                <h4 class="mt-5 mb-2">{{content.title2}}</h4>
                <p>{{content.content2|linebreaksbr}}</p>
                  <pre data-codetype="HTML"><code>{{content.code2|linebreaksbr}}</code></pre>
                <p class="mt-5">{{content.text2|linebreaksbr}}</p>
                <img class="img-fluid mt-2" id="image" src="{{content.image2.url}}" style="margin-bottom: 30px;"/>
                <p>{{content.caption2|linebreaksbr}}</p>
                <h4 class="mt-5 mb-2">{{content.title3}}</h4>
                <p>{{content.content3|linebreaksbr}}</p>
                  <pre data-codetype="HTML"><code>{{content.code3|linebreaksbr}}</code></pre>
                <p class="mt-5">{{content.text3|linebreaksbr}}</p>
                <img class="img-fluid mt-2" id="image" src="{{content.image3.url}}" style="margin-bottom: 30px;"/>
                <p>{{content.caption3|linebreaksbr}}</p>
                <h4 class="mt-5 mb-2">{{content.title4}}</h4>
                <p>{{content.content4|linebreaksbr}}</p>
                  <pre data-codetype="HTML"><code>{{content.code4|linebreaksbr}}</code></pre>
                <p class="mt-5">{{content.text4|linebreaksbr}}</p>
                <img class="img-fluid mt-2" id="image" src="{{content.image4.url}}"/>
                <p class="mt-4 mb-2">{{content.caption4|linebreaksbr}}</p>
                <p class="mt-5 mb-5">{{content.caption|linebreaksbr}}</p>
              </div>
            </div>
          </div>

        </div>


        <div class="col-sm-12 col-lg-4" style="margin-top: 50px;" id="sidebar">
          <div class="card shadow" >
            <div class="card-body">
                <h4 class="text-center">Artikel Terkait</h4>
                <ul class="list-group">
                  <a class="text-dark" id="title" href="{% url 'js:definisi' %}">
                    <li class="list-group-item">Mengenal Javascript</li>
                  </a>
                  {% for content in other_content %}
                   <a class="text-dark" id="title" href="{% url 'js:content' content.slug  %}">
                     <li class="list-group-item">{{content.title}}</li>
                    </a>
                  {% endfor %}
                </ul>
            </div>
          </div>

          <div class="card shadow mt-5 mb-5">
            <div class="card-body">
              <h4 class="text-center">Tutorial Lainnya</h4>
              <ul class="list-group">
                <a class="text-dark" id="title" href="{% url 'html:page'  %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/html.png' %}" alt="" width="30px"><span id="title">HTML</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'css:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/css.png' %}" alt="" width="30px"><span id="title">CSS</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'dom:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px"><span id="title">DOM</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'bootstrap:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px"><span id="title">Bootstrap</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'python:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px"><span id="title">Python</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'oop:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px"><span id="title">OOP</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'django:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px"><span id="title">Django</span>
                  </li>
                </a>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>

{% endblock Contents %}

jscontent/templates/javascript/content_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    Javascript
{% endblock Title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "javascript/styling/definisi.css" %}">
    <div class="container-fluid" style="margin-top: 150px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8 mb-5" id="article">
          <div class="card" style="border: none;">
            <div class="card-body">
              <h2 class="card-title" style="font-weight: bold;">Mengenal Javascript</h2>
              <hr class="bg-dark mb-5" id="hr">

              <img class="img-fluid mb-5" src="{% static 'img/cover/js.png' %}" alt="cover" width="780px">

              <div class="card-text">
                <p><em>"Javascript berguna untuk menyempurnakan sebuah tampilan dan sistem halaman web"</em></p>
                <p>JavaScript dibuat dan didesain oleh <em>Brandan Eich, seorang karyawan Netscape</em>, pada bulan September 1995. Awalnya bahasa pemrograman ini disebut <em>Mocha</em>, kemudian diganti ke <em>Mona</em>, lalu <em>LiveScript</em> sebelum akhirnya resmi menyandang nama <em>JavaScript</em>.</p>
                <p>Sejak saat itu, JavaScript terus bertumbuh dan berkembang. Pada akhirnya di tahun 2016, sebanyak 92% website diketahui menggunakan JavaScript.</p>
                <p>Javasript adalah sebuah bahasa permrograman yang khusus dirancang untuk website.</p>
                <p><i>Javascript berjalan disisi klien</i></p>
                <p>Artinya penggunaan javascript hanya terbatas pada web-browser saja, tidak dapat melakukan manipulasi data pada sisi server. Sebuah javascript diapit oleh tag <code class="text-dark">&lt;script&gt;&lt;&#47;script&gt;</code>&#46;</p>
                <p>File pada Javascript berekstensi <code class="text-dark">.js&#44; .javascript</code>.</p>

                  <pre data-codetype="HTML"><code>&lt;script language=&#34;javascript&#34;&gt;<br>  //javascripy kode disini…<br>&lt;&#47;script&gt; <br><br>Atau <br><br>&lt;script type=&#34;text&#47;javascript&#34;&gt;<br>  //javascripy kode disini….<br>&lt;&#47;script&gt;</code></pre>

                <h4 class="mt-5 mb-3">Penggunaan Kode JS</h4>
                <p>Sebenarnya sintaks javascript dengan bahasa pemrogramman lainnya itu sama yang membedakan hanya karakteristik  sintaks  dari setiap bahasa pemrogramman tersebut.<br>Sebelum menggunakan kode javascript diharapkan mengerti tentang struktur bagian dasar kode javascript, antara lain :</p>

                <!-- Struktur JS -->
                <!-- Function() -->
                <h5>Function()</h5>
                <p>Function merupakan sebuah blok kode atau beberapa baris kode pada javascript. Function juga merupakan fasilitas disetiap pemrograman untuk membuat sebuah perintah yg dapat digunakan berulangkali.</p>

                <!-- Id wrap -->
                <h5>getElementById('wrap').innerHTML = ;</h5>
                <p>getElementById('wrap') diambil element yang berdasarkan id-nya <code>&lit;div id="wrap"&gt;&lt;/div&gt;</code> jadi dapat diubah, tidak harus berId <b>wrap</b>. Lalu pada <code class="text-dark">innerHTML</code> itu dapat berisi tipe data string, tipe data angka, variabel, dll.</p>

                <!-- Parameter -->
                <h5>Parameter</h5>
                <p>Parameter adalah sebuah nilai yang akan diletakkan diantara kurung pada <code class="text-dark">function()</code> berguna untuk dapat diolah datanya di dalam fungsi itu sendiri.</p>

                <p>Contoh pada file dibawah ini : <br><br>input_js.html</p>

                  <pre data-codetype="HTML"><code=>&lt;!DOCTYPE html&gt;<br>&lt;html lang="en" dir="ltr"&gt;<br> &lt;head&gt;<br>  &lt;meta charset="utf-8"&gt;<br>  &lt;title&gt;Struktur Kode JS&lt;/title&gt;<br> &lt;/head&gt;<br> &lt;body&gt;<br>  &lt;h4&gt;Struktur Kode JS&lt;/h4&gt;<br>  &lt;!-- Id wrap --&gt;<br>  &lt;div id="hasil"&gt;&lt;/div&gt;<br>  &lt;script type="text/javascript"&gt;<br>   &lt;!--- function ---&gt;<br>   function jsKu(tempat) {<br>    &lt;!-- Parameter --&gt;<br>    var x = tempat + "Bali.";<br>    &lt;!-- Id wrap --&gt;<br>    document.getElementById("hasil").innerHTML = x ;<br>   }<br>   jsKu("Anton dan keluarga pergi ke ");<br>  &lt;/script&gt;<br> &lt;/body&gt;<br>&lt;/html&gt;</code></pre>

                <p>Output yang ditampilkan :</p>
                <img class="img-fluid mb-5" src="{% static 'img/property/js/struktur kode.png' %}" alt="">

                <!-- Penggunaan JS -->
                <p class="mt-4">Cara penggunaan sebuah  kode javascript ke dalam halaman web  hampir sama dengan css, terdapat 2 metode yaitu :</p>
                <ul style="margin-left: -15px;">
                  <!-- Internal -->
                  <li><b>Metode Internal</b>&#44; dengan memasukkan secara langsung ke dalam html. <br><br>internal.html</li>

                    <pre data-codetype="HTML"><code>&lt;!DOCTYPE html&gt;<br>&lt;html lang="en" dir="ltr"&gt;<br> &lt;head&gt;<br>  &lt;meta charset="utf-8"&gt;<br>  &lt;title&gt;Penggunaan kode JS&lt;/title&gt;<br>  &lt;/head&gt;<br> &lt;body&gt;<br>  &lt;h4&gt;Penggunaan kode JS: Metode internal&lt;/h4&gt;<br>  &lt;div id="wrap"&gt;&lt;/div&gt;<br>  &lt;script type="text/javascript"&gt;<br>   function PrintText(nama) {<br>    var text = nama + "Rio.";<br>    document.getElementById("wrap").innerHTML = text ;<br>   }<br>   PrintText("Laki - laki itu bernama ");<br>  &lt;/script&gt;<br> &lt;/body&gt;<br>&lt;/html&gt;</code></pre>

                  <p>Output yang ditampilkan</p>
                  <img class="img-fluid mb-5" src="{% static 'img/property/js/metode internal.png' %}" alt="">

                  <!-- Eksternal -->
                  <li><b>Metode Eksternal</b>&#44; dengan membuat file js terpisah.<br>Jika menggunakan metode eksternal buat file javascript terpisah. Lalu import file js tersebut pada halaman html.<br><br>eksternal.html</li>

                    <pre class="mt-3" data-codetype="HTML"><code>&lt;!DOCTYPE html&gt;<br>&lt;html lang="en" dir="ltr"&gt;<br> &lt;head&gt;<br>  &lt;meta charset="utf-8"&gt;<br>  &lt;title&gt;Penggunaan kode JS&lt;/title&gt;<br> &lt;/head&gt;<br> &lt;body&gt;<br>  &lt;h4&gt;Penggunaan Metode Eksternal JS&lt;/h4&gt;<br>  &lt;div id="wrap"&gt;&lt;/div&gt;<br>  &lt;script type="text/javascript" src="../Javascript/scripts.js"&gt;&lt;/script&gt;<br> &lt;/body&gt;<br>&lt;/html&gt;
                    </code></pre>

                  <p class="mt-5">scripts.js</p>

                    <pre data-codetype="HTML"><code>function PrintText(nama) {<br>  var text = nama + "Talita.";<br>  document.getElementById("wrap").innerHTML = text ;<br>}<br>PrintText("Wanita itu bernama ");</code></pre>

                  <p>Output yang ditampilkan :</p>
                  <img class="img-fluid mb-5" src="{% static 'img/property/js/metode eksternal.png' %}" alt="">
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-lg-4" id="sidebar">
          <div class="card shadow" >
            <div class="card-body">
                <h4 class="text-center">Artikel Terkait</h4>
                <ul class="list-group">
                  {% for content in content_list %}
                   <a class="text-dark" id="title" href="{% url 'js:content' content.slug %}">
                     <li class="list-group-item">{{content.title}}</li>
                    </a>
                  {% endfor %}
                </ul>
            </div>
          </div>

          <div class="card shadow mt-5 mb-5">
            <div class="card-body">
              <h4 class="text-center">Tutorial Lainnya</h4>
              <ul class="list-group">
                <a class="text-dark" id="title" href="{% url 'html:page'  %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/html.png' %}" alt="" width="30px"><span id="title">HTML</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'css:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/css.png' %}" alt="" width="30px"><span id="title">CSS</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'dom:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px"><span id="title">DOM</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'bootstrap:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px"><span id="title">Bootstrap</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'python:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px"><span id="title">Python</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'oop:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px"><span id="title">OOP</span>
                  </li>
                </a>
                <a class="text-dark" id="title" href="{% url 'django:page' %}">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px"><span id="title">Django</span>
                  </li>
                </a>
              </ul>
              </div>
          </div>
        </div>
      </div>
    </div>



{% endblock Contents %}

jscontent/templates/javascript/page_list.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    Javascript
{% endblock Title %}

{% block page_title %}
  <div class="jumbotron-fluid ml-5">
      <h1 class="display-4 text-dark">Javascript</h1>
      <h2 class="text-dark mb-5">Tutorial bagi para pemula</h2>
  </div>
{% endblock page_title %}

{% block Contents %}
    <link rel="stylesheet" href="{% static "javascript/styling/page.css" %}">

    <div class="container-fluid" style="margin-bottom: 200px;">
      <div class="row">

        <div class="col-sm-12 col-lg-8 mb-5" id="article">
          <div class="card shadow">
            <div class="card-body">
              <a href="{% url 'js:definisi' %}" class="text-dark" id="title">Mengenal Javascript</a>
            </div>
          </div>
          {% for content in content_list  %}
            <div class="card shadow">
              <div class="card-body">
                <a href="{% url 'js:content' content.slug %}" class="text-dark" id="title">{{content.title}}</a>
              </div>
            </div>
          {% endfor %}
        </div>

        <div class="col-sm-12 col-lg-4" id="sidebar">
          <div class="card shadow">
            <div class="card-body">
              <h3 class="text-center">Tutorial Lainnya</h3>
              <ul class="list-group">
                <a href="{% url 'html:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/html.png' %}" alt="" width="30px">
                    <span id="title">HTML</span>
                  </li>
                </a>
                <a href="{% url 'css:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/css.png' %}" alt="" width="30px">
                    <span id="title">CSS</span>
                  </li>
                </a>
                <a href="{% url 'dom:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/dom.png' %}" alt="" width="30px">
                    <span id="title">DOM</span>
                  </li>
                </a>
                <a href="{% url 'bootstrap:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/bootstrap.png' %}" alt="" width="30px">
                    <span id="title">Bootstrap</span>
                  </li>
                </a>
                <a href="{% url 'python:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/python.png' %}" alt="" width="30px">
                    <span id="title">Python</span>
                  </li>
                </a>
                <a href="{% url 'oop:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/oop.png' %}" alt="" width="30px">
                    <span id="title">OOP</span>
                  </li>
                </a>
                <a href="{% url 'django:page' %}" class="text-dark" id="title">
                  <li class="list-group-item">
                    <img src="{% static 'img/logo/django.png' %}" alt="" width="30px">
                    <span id="title">Django</span>
                  </li>
                </a>
              </ul>
            </div>
          </div>
        </div>

        </div>
      </div>



{% endblock Contents %}