blog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ContentDetail.as_view(), name = 'content'),
    url(r'^$', Page.as_view(), name = 'page'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from .views import *

urlpatterns = [
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^django/', include('djangocontent.urls', namespace = 'django')),
    url(r'^oop/', include('oopcontent.urls', namespace = 'oop')),
    url(r'^python/', include('pythoncontent.urls', namespace = 'python')),
    url(r'^bootstrap/', include('bootstrapcontent.urls', namespace = 'bootstrap')),
    url(r'^dom/', include('domcontent.urls', namespace = 'dom' )),
    url(r'^js/', include('jscontent.urls', namespace = 'js' )),
    url(r'^css/', include('csscontent.urls', namespace = 'css' )),
    url(r'^html/', include('htmlcontent.urls', namespace = 'html' )),
    url(r'^tutorial/$', Tutorial.as_view(), name='tutorial'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>tunaskode.com</title>
    <!--- FILE BOOTSTRAP ------>
        {% include "snippets/styles.html" %}
    <link rel="stylesheet" href="{% static "styling/home.css" %}">
  </head>


  <body>
    {% include "snippets/nav.html" %}

    <div class="jumbotron jumbotron-fluid" style="height: 600px;">
      <!--JUMBROTON HOME---->
        <div class="container">
          <h1 class="title display-4">Tutorial Bagi Pemula</h1>
          <h3 class="lead display-5 text-center">Memuat dasar bahasa pemogramman html, css, javascript, python.</h3>
          <p class="lead" style="margin-left: 21%;">
            <a class="btn btn-default btn-md" href="{% url 'tutorial' %}" role="button">Belajar</a>
          </p>
        </div>
    </div>

    <div class="container  mb-5" style="height: 700px;">
      <div class="card-deck">
        {% for content in latest_content %}
          <div class="card mx-auto">
            <a href="{% url 'blog:content' content.slug %}"><img class="card-img-top" src="{{content.cover.url}}" alt="Card image cap"></a>
            <div class="card-body">
              <a id="title" href="{% url 'blog:content' content.slug %}">
                <h5 class="card-title text-dark">{{content.title}}</h5>
                <p class="card-text text-dark">{{content.content|truncatewords:15}}</p>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>

    <footer class="page-footer font-small">
      <div class="container text-center py-3">&copy; 2020
        <a href="{% url 'home'%}"> tunaskode.com</a>
      </div>
    </footer>
    <!-- FILE BOOTSTRAP -->
    {% include "snippets/scripts.html" %}


  </body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
      {% block Title %}
          tunaskode.com
      {% endblock Title %}
    </title>
    <link rel="stylesheet" href="{% static "styling/index.css" %}">
  </head>
      {% include "snippets/styles.html" %}


  <body>
      {% include "snippets/nav.html" %}

      {% block page_title %}

      {% endblock page_title %}

      {% block Contents %}

      {% endblock Contents %}






    {% include "snippets/scripts.html" %}


  </body>
</html>

templates/tutor.html
{% extends "index.html" %}
{% load static %}

{% block Title %}
    tutorial
{% endblock Title %}

{% block page_title %}
  <div class="jumbotron-fluid ml-5 mr-5">
    <div class="card shadow">
        <h1 class="text-center p-5 display-4" style="font-weight: bold;">Ingin belajar apa hari ini ?</h1>
    </div>
  </div>

{% endblock page_title %}

{% block Contents %}
  <link rel="stylesheet" href="{% static "styling/index.css" %}">
  <div class="container my-5">
    <div class="row row-cols-md-2 row-cols-sm-3 row-cols-2 d-flex justify-content-between" style="margin-bottom: 250px;">
      <div class="col-md-3 mb-5 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;"  href="{% url 'html:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/html.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">HTML</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mb-5 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'css:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/css.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">CSS</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mb-5 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'js:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/js.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">Javascript</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mb-5 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'dom:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/dom.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">DOM</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'bootstrap:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/bootstrap.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">Bootstrap</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'python:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/python.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">Python</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'oop:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/oop.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">OOP</div>
          </a>
        </div>
      </div>

      <div class="col-md-3 mt-5">
        <div class="text-center">
          <a style="text-decoration: none;" href="{% url 'django:page' %}">
            <div class="col-sm">
              <img class="img-responsive mb-5" src="{% static 'img/logo/django.png' %}" alt="">
            </div>
            <div class="card-footer text-dark shadow">Django</div>
          </a>
        </div>
      </div>
  </div>

{% endblock Contents %}